/**
 * 奇易智能导航系统 - 完整链接数据文件
 * 版本: 13.4
 * 作者: 奇易科技
 * 功能: 存储所有默认链接数据，支持九大分类，每个分类35个链接
 */

/**
 * 获取默认链接数据
 * @returns {Object} 默认链接数据
 */
function getDefaultLinkData() {
    return {
        // 推荐网址 (35个)
        recommended: [
            {name: "腾讯", url: "https://www.qq.com/", class: "", id: "rec_001"},
            {name: "网易", url: "https://www.163.com/", class: "", id: "rec_002"},
            {name: "搜狐", url: "https://www.sohu.com/", class: "", id: "rec_003"},
            {name: "新浪", url: "https://www.sina.com.cn/", class: "", id: "rec_004"},
            {name: "凤凰网", url: "https://www.ifeng.com/", class: "", id: "rec_005"},
            {name: "央视网", url: "https://www.cctv.com/", class: "", id: "rec_006"},
            {name: "中国移动", url: "https://www.10086.cn/", class: "", id: "rec_007"},
            {name: "人民网", url: "https://www.people.com.cn/", class: "", id: "rec_008"},
            {name: "农业银行", url: "https://www.abchina.com/cn/", class: "", id: "rec_009"},
            {name: "东莞农商银行", url: "https://www.drcbank.com/", class: "", id: "rec_010"},
            {name: "中国银行", url: "https://www.boc.cn/", class: "", id: "rec_011"},
            {name: "Excel Home", url: "https://club.excelhome.net/", class: "", id: "rec_012"},
            {name: "Access中国", url: "https://www.access-cn.com/", class: "", id: "rec_013"},
            {name: "12306", url: "https://www.12306.cn/", class: "", id: "rec_014"},
            {name: "Facebook", url: "https://www.facebook.com/", class: "", id: "rec_015"},
            {name: "黑罐头", url: "https://www.heycan.com/", class: "", id: "rec_016"},
            {name: "中国人寿", url: "https://www.chinalife.com.cn/", class: "", id: "rec_017"},
            {name: "TikTok", url: "https://www.tiktok.com/", class: "", id: "rec_018"},
            {name: "今日头条", url: "https://mp.toutiao.com/", class: "", id: "rec_019"},
            {name: "花生壳", url: "https://www.oray.com/", class: "", id: "rec_020"},
            {name: "优课星球", url: "https://pc.ukxq.com/", class: "", id: "rec_021"},
            {name: "海洋学院", url: "https://www.weitianxia.club/", class: "", id: "rec_022"},
            {name: "支付牌照", url: "https://www.pbc.gov.cn/", class: "", id: "rec_023"},
            {name: "微软电脑管家", url: "https://pcmanager.microsoft.com/", class: "", id: "rec_024"},
            {name: "淘宝", url: "https://www.taobao.com/", class: "", id: "rec_025"},
            {name: "闲鱼", url: "https://www.goofish.com/", class: "", id: "rec_026"},
            {name: "晨枫U盘", url: "https://www.myfeng.cn/", class: "", id: "rec_027"},
            {name: "百度翻译", url: "https://fanyi.baidu.com/", class: "", id: "rec_028"},
            {name: "GitHub", url: "https://github.com/", class: "", id: "rec_029"},
            {name: "开源PE", url: "https://www.hotpe.top/", class: "", id: "rec_030"},
            {name: "MDN Web Docs", url: "https://developer.mozilla.org/", class: "", id: "rec_031"},
            {name: "W3Schools", url: "https://www.w3schools.com/", class: "", id: "rec_032"},
            {name: "知乎", url: "https://www.zhihu.com/", class: "", id: "rec_033"},
            {name: "豆瓣", url: "https://www.douban.com/", class: "", id: "rec_034"},
            {name: "B站", url: "https://www.bilibili.com/", class: "", id: "rec_035"}
        ],

        // 代理系统 (35个)
        proxy: [
            {name: "微商通系统", url: "https://www.mywst.com/", class: "", id: "pro_001"},
            {name: "营销系统", url: "https://cms.dlszyht.com/", class: "", id: "pro_002"},
            {name: "爱奇艺号", url: "https://mp.iqiyi.com/", class: "", id: "pro_003"},
            {name: "企鹅号", url: "https://om.qq.com/", class: "", id: "pro_004"},
            {name: "大鱼号", url: "https://mp.dayu.com/", class: "", id: "pro_005"},
            {name: "百家号", url: "https://baijiahao.baidu.com/", class: "", id: "pro_006"},
            {name: "头条号", url: "https://mp.toutiao.com/", class: "", id: "pro_007"},
            {name: "网易号", url: "https://mp.163.com/", class: "", id: "pro_008"},
            {name: "趣头条号", url: "https://mp.qutoutiao.net/", class: "", id: "pro_009"},
            {name: "惠头条号", url: "https://mp.cashtoutiao.com/", class: "", id: "pro_010"},
            {name: "新浪看点", url: "https://mp.sina.com.cn/", class: "", id: "pro_011"},
            {name: "哔哩哔哩创作", url: "https://member.bilibili.com/", class: "", id: "pro_012"},
            {name: "视频号助手", url: "https://channels.weixin.qq.com/", class: "", id: "pro_013"},
            {name: "微信客服", url: "https://mpkf.weixin.qq.com/", class: "", id: "pro_014"},
            {name: "微信公众号", url: "https://mp.weixin.qq.com/", class: "", id: "pro_015"},
            {name: "抖店", url: "https://fxg.jinritemai.com/", class: "", id: "pro_016"},
            {name: "新区云", url: "https://www.xinquyun.com/", class: "", id: "pro_017"},
            {name: "U钙网LOGO", url: "https://www.uugai.com/", class: "", id: "pro_018"},
            {name: "IP检测1", url: "https://ipip.la/", class: "", id: "pro_019"},
            {name: "IP检测2", url: "https://www.itdog.cn/", class: "", id: "pro_020"},
            {name: "收钱吧商家", url: "https://s.shouqianba.com/", class: "", id: "pro_021"},
            {name: "微信服务商", url: "https://fuwu.weixin.qq.com/", class: "", id: "pro_022"},
            {name: "收钱吧掌柜", url: "https://sales-web.shouqianba.com/", class: "", id: "pro_023"},
            {name: "微信开放平台", url: "https://open.weixin.qq.com/", class: "", id: "pro_024"},
            {name: "支付宝开放平台", url: "https://open.alipay.com/", class: "", id: "pro_025"},
            {name: "抖音开放平台", url: "https://open.douyin.com/", class: "", id: "pro_026"},
            {name: "百度小程序", url: "https://smartprogram.baidu.com/", class: "", id: "pro_027"},
            {name: "微信小程序", url: "https://mp.weixin.qq.com/", class: "", id: "pro_028"},
            {name: "支付宝小程序", url: "https://mini.open.alipay.com/", class: "", id: "pro_029"},
            {name: "字节跳动小程序", url: "https://microapp.bytedance.com/", class: "", id: "pro_030"},
            {name: "快手小程序", url: "https://mp.kuaishou.com/", class: "", id: "pro_031"},
            {name: "360小程序", url: "https://mp.360.cn/", class: "", id: "pro_032"},
            {name: "华为快应用", url: "https://developer.huawei.com/", class: "", id: "pro_033"},
            {name: "小米快应用", url: "https://dev.mi.com/", class: "", id: "pro_034"},
            {name: "OPPO快应用", url: "https://open.oppomobile.com/", class: "", id: "pro_035"}
        ],

        // 内部系统 (35个)
        internal: [
            {name: "内部管理系统", url: "http://192.168.1.100/", class: "blue", id: "int_001"},
            {name: "OA办公系统", url: "http://192.168.1.101/", class: "green", id: "int_002"},
            {name: "CRM客户系统", url: "http://192.168.1.102/", class: "orange", id: "int_003"},
            {name: "ERP企业系统", url: "http://192.168.1.103/", class: "purple", id: "int_004"},
            {name: "项目管理", url: "http://192.168.1.104/", class: "blue", id: "int_005"},
            {name: "人力资源系统", url: "http://192.168.1.105/", class: "green", id: "int_006"},
            {name: "财务系统", url: "http://192.168.1.106/", class: "orange", id: "int_007"},
            {name: "知识库系统", url: "http://192.168.1.107/", class: "purple", id: "int_008"},
            {name: "文档中心", url: "http://192.168.1.108/", class: "blue", id: "int_009"},
            {name: "邮件系统", url: "http://192.168.1.109/", class: "green", id: "int_010"},
            {name: "会议系统", url: "http://192.168.1.110/", class: "orange", id: "int_011"},
            {name: "VPN系统", url: "http://192.168.1.111/", class: "purple", id: "int_012"},
            {name: "监控系统", url: "http://192.168.1.112/", class: "blue", id: "int_013"},
            {name: "日志系统", url: "http://192.168.1.113/", class: "green", id: "int_014"},
            {name: "备份系统", url: "http://192.168.1.114/", class: "orange", id: "int_015"},
            {name: "测试系统", url: "http://192.168.1.115/", class: "purple", id: "int_016"},
            {name: "开发环境", url: "http://192.168.1.116/", class: "blue", id: "int_017"},
            {name: "预发布环境", url: "http://192.168.1.117/", class: "green", id: "int_018"},
            {name: "生产环境", url: "http://192.168.1.118/", class: "orange", id: "int_019"},
            {name: "API网关", url: "http://192.168.1.119/", class: "purple", id: "int_020"},
            {name: "数据库管理", url: "http://192.168.1.120/", class: "blue", id: "int_021"},
            {name: "缓存管理", url: "http://192.168.1.121/", class: "green", id: "int_022"},
            {name: "消息队列", url: "http://192.168.1.122/", class: "orange", id: "int_023"},
            {name: "容器管理", url: "http://192.168.1.123/", class: "purple", id: "int_024"},
            {name: "CI/CD系统", url: "http://192.168.1.124/", class: "blue", id: "int_025"},
            {name: "代码仓库", url: "http://192.168.1.125/", class: "green", id: "int_026"},
            {name: "制品仓库", url: "http://192.168.1.126/", class: "orange", id: "int_027"},
            {name: "安全中心", url: "http://192.168.1.127/", class: "purple", id: "int_028"},
            {name: "合规中心", url: "http://192.168.1.128/", class: "blue", id: "int_029"},
            {name: "审计系统", url: "http://192.168.1.129/", class: "green", id: "int_030"},
            {name: "报表系统", url: "http://192.168.1.130/", class: "orange", id: "int_031"},
            {name: "BI系统", url: "http://192.168.1.131/", class: "purple", id: "int_032"},
            {name: "数据仓库", url: "http://192.168.1.132/", class: "blue", id: "int_033"},
            {name: "大数据平台", url: "http://192.168.1.133/", class: "green", id: "int_034"},
            {name: "人工智能平台", url: "http://192.168.1.134/", class: "orange", id: "int_035"}
        ],

        // 软件工具 (35个)
        software: [
            {name: "Photopea", url: "https://www.photopea.com/", class: "", id: "sof_001"},
            {name: "在线PS", url: "https://ps.gaoding.com/", class: "", id: "sof_002"},
            {name: "Canva", url: "https://www.canva.cn/", class: "", id: "sof_003"},
            {name: "Figma", url: "https://www.figma.com/", class: "", id: "sof_004"},
            {name: "VSCode在线", url: "https://vscode.dev/", class: "", id: "sof_005"},
            {name: "GitHub", url: "https://github.com/", class: "", id: "sof_006"},
            {name: "GitLab", url: "https://gitlab.com/", class: "", id: "sof_007"},
            {name: "CodePen", url: "https://codepen.io/", class: "", id: "sof_008"},
            {name: "JSFiddle", url: "https://jsfiddle.net/", class: "", id: "sof_009"},
            {name: "CodeSandbox", url: "https://codesandbox.io/", class: "", id: "sof_010"},
            {name: "Replit", url: "https://replit.com/", class: "", id: "sof_011"},
            {name: "Glitch", url: "https://glitch.com/", class: "", id: "sof_012"},
            {name: "StackBlitz", url: "https://stackblitz.com/", class: "", id: "sof_013"},
            {name: "JSON格式化", url: "https://jsonformatter.org/", class: "", id: "sof_014"},
            {name: "Base64编码", url: "https://www.base64encode.org/", class: "", id: "sof_015"},
            {name: "二维码生成", url: "https://www.qr-code-generator.com/", class: "", id: "sof_016"},
            {name: "颜色选择器", url: "https://htmlcolorcodes.com/", class: "", id: "sof_017"},
            {name: "Font Awesome", url: "https://fontawesome.com/", class: "", id: "sof_018"},
            {name: "图标查找", url: "https://www.iconfinder.com/", class: "", id: "sof_019"},
            {name: "Unsplash", url: "https://unsplash.com/", class: "", id: "sof_020"},
            {name: "Pexels", url: "https://www.pexels.com/", class: "", id: "sof_021"},
            {name: "Pixabay", url: "https://pixabay.com/", class: "", id: "sof_022"},
            {name: "TinyPNG", url: "https://tinypng.com/", class: "", id: "sof_023"},
            {name: "SmallPDF", url: "https://smallpdf.com/", class: "", id: "sof_024"},
            {name: "在线录屏", url: "https://screenapp.io/", class: "", id: "sof_025"},
            {name: "流程图", url: "https://app.diagrams.net/", class: "", id: "sof_026"},
            {name: "思维导图", url: "https://www.mindmeister.com/", class: "", id: "sof_027"},
            {name: "在线白板", url: "https://miro.com/", class: "", id: "sof_028"},
            {name: "代码对比", url: "https://www.diffchecker.com/", class: "", id: "sof_029"},
            {name: "飞牛fnOS", url: "https://www.fnnas.com/", class: "", id: "sof_030"},
            {name: "正版系统", url: "https://msdn.itellyou.cn/?lang=zh-cn", class: "", id: "sof_031"},
            {name: "Markdown编辑器", url: "https://stackedit.io/", class: "", id: "sof_032"},
            {name: "QQ五笔输入法", url: "https://pc.qq.com/detail/7/detail_207.html", class: "", id: "sof_033"},
            {name: "微软电脑管家", url: "https://pcmanager.microsoft.com/zh-cn", class: "", id: "sof_034"},
            {name: "网页快照", url: "https://archive.org/web/", class: "", id: "sof_035"}
        ],

        // 在线业务 (35个)
        business: [
            {name: "阿里云", url: "https://www.aliyun.com/", class: "", id: "bus_001"},
            {name: "腾讯云", url: "https://cloud.tencent.com/", class: "", id: "bus_002"},
            {name: "华为云", url: "https://www.huaweicloud.com/", class: "", id: "bus_003"},
            {name: "亚马逊AWS", url: "https://aws.amazon.com/", class: "", id: "bus_004"},
            {name: "国家知识产权局", url: "https://sso.cnipa.gov.cn/am/#/login", class: "", id: "bus_005"},
            {name: "谷歌云", url: "https://cloud.google.com/", class: "", id: "bus_006"},
            {name: "七牛云", url: "https://www.qiniu.com/", class: "", id: "bus_007"},
            {name: "又拍云", url: "https://www.upyun.com/", class: "", id: "bus_008"},
            {name: "UCloud", url: "https://www.ucloud.cn/", class: "", id: "bus_009"},
            {name: "金山云", url: "https://www.ksyun.com/", class: "", id: "bus_010"},
            {name: "百度云", url: "https://cloud.baidu.com/", class: "", id: "bus_011"},
            {name: "京东云", url: "https://www.jdcloud.com/", class: "", id: "bus_012"},
            {name: "新浪云", url: "https://www.sinacloud.com/", class: "", id: "bus_013"},
            {name: "美团云", url: "https://www.mtyun.com/", class: "", id: "bus_014"},
            {name: "滴滴云", url: "https://www.didiyun.com/", class: "", id: "bus_015"},
            {name: "网易云", url: "https://www.163yun.com/", class: "", id: "bus_016"},
            {name: "苏宁云", url: "https://cloud.suning.com/", class: "", id: "bus_017"},
            {name: "青云", url: "https://www.qingcloud.com/", class: "", id: "bus_018"},
            {name: "天翼云", url: "https://www.ctyun.cn/", class: "", id: "bus_019"},
            {name: "移动云", url: "https://cloud.10086.cn/", class: "", id: "bus_020"},
            {name: "联通云", url: "https://cloud.10010.com/", class: "", id: "bus_021"},
            {name: "电信云", url: "https://cloud.189.cn/", class: "", id: "bus_022"},
            {name: "世纪互联", url: "https://www.21vianet.com/", class: "", id: "bus_023"},
            {name: "西部数码", url: "https://www.west.cn/", class: "", id: "bus_024"},
            {name: "新网", url: "https://www.xinnet.com/", class: "", id: "bus_025"},
            {name: "万网", url: "https://www.net.cn/", class: "", id: "bus_026"},
            {name: "GoDaddy", url: "https://www.godaddy.com/", class: "", id: "bus_027"},
            {name: "Namecheap", url: "https://www.namecheap.com/", class: "", id: "bus_028"},
            {name: "HostGator", url: "https://www.hostgator.com/", class: "", id: "bus_029"},
            {name: "Bluehost", url: "https://www.bluehost.com/", class: "", id: "bus_030"},
            {name: "SiteGround", url: "https://www.siteground.com/", class: "", id: "bus_031"},
            {name: "DreamHost", url: "https://www.dreamhost.com/", class: "", id: "bus_032"},
            {name: "小程序管理", url: "https://www.dzos.top/new_plat/index.html#/login", class: "", id: "bus_033"},
            {name: "飞书", url: "https://accounts.feishu.cn/accounts/page/login?app_id=7&no_trap=1&redirect_uri=https%3A%2F%2Fopen.feishu.cn%2Fapp", class: "", id: "bus_034"},
            {name: "微软电脑管家", url: "https://pcmanager.microsoft.com/zh-cn", class: "", id: "bus_035"}
        ],

        // 常用网址 (35个)
        common: [
            {name: "微信支付", url: "https://pay.weixin.qq.com/", class: "", id: "com_001"},
            {name: "投资项目", url: "https://tzxm.gd.gov.cn/", class: "", id: "com_002"},
            {name: "腾讯地图", url: "https://map.qq.com/", class: "", id: "com_003"},
            {name: "国家知识产权局", url: "https://sso.cnipa.gov.cn/am/#/login", class: "", id: "com_004"},
            {name: "软件登记官网", url: "https://www.ccopyright.com.cn/", class: "", id: "com_005"},
            {name: "专利申请官网", url: "https://cponline.cnipa.gov.cn/", class: "", id: "com_006"},
            {name: "佛山市扶持通", url: "https://fsfczj.foshan.gov.cn", class: "", id: "com_007"},
            {name: "熊猫办公", url: "https://www.tukuppt.com/", class: "", id: "com_008"},
            {name: "群志SRM系统", url: "https://nhvp.innolux.com/", class: "", id: "com_009"},
            {name: "群创厂商", url: "https://www.innolux.com/", class: "", id: "com_010"},
            {name: "周易雅说", url: "https://h5.qlchat.com/", class: "", id: "com_011"},
            {name: "日丰企业", url: "https://srm.rifeng.com.cn/", class: "", id: "com_012"},
            {name: "群创线上报价", url: "https://epmall.innolux.com/", class: "", id: "com_013"},
            {name: "东莞社保局", url: "https://www.dgsi.gov.cn/", class: "", id: "com_014"},
            {name: "物品编码中心", url: "https://www.ancc.org.cn/", class: "", id: "com_015"},
            {name: "电子证照查验", url: "https://zzcy.dg.cn/", class: "", id: "com_016"},
            {name: "经营范围查验", url: "https://jyfwyun.com/", class: "", id: "com_017"},
            {name: "国税", url: "https://www.etax-gd.gov.cn/", class: "", id: "com_018"},
            {name: "海南e登记", url: "https://e-register.amr.hainan.gov.cn/icpsp-web-pc/#/index/page", class: "", id: "com_019"},
            {name: "广东政务服务网", url: "https://www.gdzwfw.gov.cn/", class: "", id: "com_020"},
            {name: "个人信用查询", url: "https://ipcrs.pbccrc.org.cn/", class: "", id: "com_021"},
            {name: "国家税务总局", url: "https://www.chinatax.gov.cn/", class: "", id: "com_022"},
            {name: "国家知识产权局", url: "https://www.cnipa.gov.cn/", class: "", id: "com_023"},
            {name: "微信支付", url: "https://pay.weixin.qq.com/", class: "", id: "com_024"},
            {name: "征信中心", url: "https://www.pbccrc.org.cn/", class: "", id: "com_025"},
            {name: "裁判文书网", url: "https://wenshu.court.gov.cn/", class: "", id: "com_026"},
            {name: "执行信息公开网", url: "https://zxgk.court.gov.cn/", class: "", id: "com_027"},
            {name: "企业信用公示", url: "https://www.gsxt.gov.cn/", class: "", id: "com_028"},
            {name: "国家政务服务平台", url: "https://gjzwfw.www.gov.cn/", class: "", id: "com_029"},
            {name: "专利查询", url: "https://epub.sipo.gov.cn/", class: "", id: "com_030"},
            {name: "驾驶证查询", url: "https://jia.122.gov.cn/", class: "", id: "com_031"},
            {name: "车辆年检", url: "https://www.12312.gov.cn/", class: "", id: "com_032"},
            {name: "交通违法", url: "https://gd.122.gov.cn/", class: "", id: "com_033"},
            {name: "交通事故", url: "https://www.122.cn/", class: "", id: "com_034"},
            {name: "交通法规", url: "https://www.mps.gov.cn/", class: "", id: "com_035"}
        ],

        // 财务理财 (35个)
        finance: [
            {name: "微淼财商", url: "https://www.weimiao.cn/", class: "", id: "fin_001"},
            {name: "中证指数", url: "https://www.csindex.com.cn/", class: "", id: "fin_002"},
            {name: "天天基金", url: "https://fund.eastmoney.com/", class: "", id: "fin_003"},
            {name: "晨星基金", url: "https://cn.morningstar.com/", class: "", id: "fin_004"},
            {name: "i问财", url: "https://www.iwencai.com/", class: "", id: "fin_005"},
            {name: "雪球", url: "https://xueqiu.com/", class: "", id: "fin_006"},
            {name: "萝卜投研", url: "https://robo.datayes.com/", class: "", id: "fin_007"},
            {name: "理杏仁", url: "https://www.lixinger.com/", class: "", id: "fin_008"},
            {name: "雪球信息网", url: "https://xueqiu.com/", class: "", id: "fin_009"},
            {name: "富途牛牛", url: "https://www.futuhk.com/", class: "", id: "fin_010"},
            {name: "上交所", url: "https://www.sse.com.cn/", class: "", id: "fin_011"},
            {name: "深交所", url: "https://www.szse.cn/", class: "", id: "fin_012"},
            {name: "港交所", url: "https://www.hkex.com.hk/", class: "", id: "fin_013"},
            {name: "国家统计局", url: "https://www.stats.gov.cn/", class: "", id: "fin_014"},
            {name: "中国人民银行", url: "https://www.pbc.gov.cn/", class: "", id: "fin_015"},
            {name: "巨潮资讯", url: "https://www.cninfo.com.cn/", class: "", id: "fin_016"},
            {name: "统计数据", url: "https://data.stats.gov.cn/", class: "", id: "fin_017"},
            {name: "同花顺个股", url: "https://stockpage.10jqka.com.cn/", class: "", id: "fin_018"},
            {name: "国家外汇局", url: "https://www.safe.gov.cn/", class: "", id: "fin_019"},
            {name: "财政部", url: "https://www.mof.gov.cn/", class: "", id: "fin_020"},
            {name: "A股市盈率", url: "https://value500.com/PE.asp", class: "", id: "fin_021"},
            {name: "恒生市盈率", url: "https://value500.com/hsipe.html", class: "", id: "fin_022"},
            {name: "国债收益率", url: "https://value500.com/Bond.asp", class: "", id: "fin_023"},
            {name: "手机国债", url: "https://cn.investing.com/", class: "", id: "fin_024"},
            {name: "深圳市盈率", url: "https://www.legulegu.com/", class: "", id: "fin_025"},
            {name: "房贷计算器", url: "https://www.fangdaijisuanqi.com/", class: "", id: "fin_026"},
            {name: "实操练习", url: "https://rongming.mikecrm.com/", class: "", id: "fin_027"},
            {name: "集思录可转债", url: "https://www.jisilu.cn/", class: "", id: "fin_028"},
            {name: "锦程消费金融", url: "https://www.jccfc.com/", class: "", id: "fin_029"},
            {name: "工具大全", url: "https://rongming.mikecrm.com/", class: "", id: "fin_030"},
            {name: "理财计算器", url: "https://m.weimiao.cn/", class: "", id: "fin_031"},
            {name: "证券时报", url: "https://www.stcn.com/", class: "", id: "fin_032"},
            {name: "中国证券报", url: "https://www.cs.com.cn/", class: "", id: "fin_033"},
            {name: "上海证券报", url: "https://www.cnstock.com/", class: "", id: "fin_034"},
            {name: "证券日报", url: "https://www.zqrb.cn/", class: "", id: "fin_035"}
        ],

        // 工作工具 (35个)
        work: [
            {name: "飞书", url: "https://www.feishu.cn/", class: "", id: "wor_001"},
            {name: "上隆自动化", url: "https://www.sl-fa.com/", class: "", id: "wor_002"},
            {name: "制造云", url: "https://www.zhizaoyun.com/", class: "", id: "wor_003"},
            {name: "迈迪网", url: "https://www.maidiyun.com/", class: "", id: "wor_004"},
            {name: "米思米", url: "https://www.misumi.com.cn/", class: "", id: "wor_005"},
            {name: "迈迪设计宝", url: "https://www.maidiyun.com/", class: "", id: "wor_006"},
            {name: "嘉立创工具箱", url: "https://ican.jlc.com/", class: "", id: "wor_007"},
            {name: "凡一自动化", url: "https://www.forrun.cn/", class: "", id: "wor_008"},
            {name: "轴承型号查询", url: "https://c.zcwz.com/", class: "", id: "wor_009"},
            {name: "三维资源在线", url: "https://www.3dsource.cn/", class: "", id: "wor_010"},
            {name: "三菱机电", url: "https://cn.mitsubishielectric.com/", class: "", id: "wor_011"},
            {name: "我要自学网", url: "https://www.51zxw.net/", class: "", id: "wor_012"},
            {name: "我爱自学网", url: "https://www.52zxw.com/", class: "", id: "wor_013"},
            {name: "软件自学网", url: "https://www.rjzxw.com/", class: "", id: "wor_014"},
            {name: "上银科技", url: "https://www.hiwin.cn/", class: "", id: "wor_015"},
            {name: "怡合达自动化", url: "https://www.yhdfa.com/", class: "", id: "wor_016"},
            {name: "猪八戒", url: "https://www.zbj.com/", class: "", id: "wor_017"},
            {name: "云智图", url: "https://www.yunzhitu.com/", class: "", id: "wor_018"},
            {name: "大学仕", url: "https://www.dxueshi.com/", class: "", id: "wor_019"},
            {name: "云工网", url: "https://www.yungong.com/", class: "", id: "wor_020"},
            {name: "橙色云", url: "https://www.orangecds.com/", class: "", id: "wor_021"},
            {name: "沐风众包", url: "https://zb.mfcad.com/", class: "", id: "wor_022"},
            {name: "一品威客", url: "https://www.epwk.com/", class: "", id: "wor_023"},
            {name: "CAD自学网", url: "https://www.cadzxw.com/", class: "", id: "wor_024"},
            {name: "钣金展开放样", url: "https://www.banjin.com/", class: "", id: "wor_025"},
            {name: "机械设计手册", url: "https://www.jixiesheji.com/", class: "", id: "wor_026"},
            {name: "中国制造网", url: "https://www.made-in-china.com/", class: "", id: "wor_027"},
            {name: "阿里巴巴", url: "https://www.1688.com/", class: "", id: "wor_028"},
            {name: "慧聪网", url: "https://www.hc360.com/", class: "", id: "wor_029"},
            {name: "百度文库", url: "https://wenku.baidu.com/", class: "", id: "wor_030"},
            {name: "道客巴巴", url: "https://www.doc88.com/", class: "", id: "wor_031"},
            {name: "豆丁网", url: "https://www.docin.com/", class: "", id: "wor_032"},
            {name: "金锄头文库", url: "https://www.jinchutou.com/", class: "", id: "wor_033"},
            {name: "原创力文档", url: "https://max.book118.com/", class: "", id: "wor_034"},
            {name: "学科网", url: "https://www.zxxk.com/", class: "", id: "wor_035"}
        ],

        // AI工具 (35个)
        side: [
            {name: "数字人AI", url: "https://www.cloudnsa.cn/super", class: "", id: "ai_001"},
            {name: "百度AI", url: "https://chat.baidu.com/", class: "", id: "ai_002"},
            {name: "Monica", url: "https://monica.cn/", class: "", id: "ai_003"},
            {name: "Kimi", url: "https://www.kimi.com/", class: "", id: "ai_004"},
            {name: "DeepSeek", url: "https://www.deepseek.com/", class: "", id: "ai_005"},
            {name: "即梦AI", url: "https://jimeng.jianying.com/", class: "", id: "ai_006"},
            {name: "Ubuntu系统", url: "https://ubuntu.com/", class: "", id: "ai_007"},
            {name: "百度数字员工", url: "https://xiling.cloud.baidu.com/", class: "", id: "ai_008"},
            {name: "Raphael AI", url: "https://raphael.app/", class: "", id: "ai_009"},
            {name: "AIGC导航", url: "https://www.aigc.cn/", class: "", id: "ai_010"},
            {name: "文件转换器", url: "https://convertio.co/", class: "", id: "ai_011"},
            {name: "AI换图", url: "https://www.linkfox.com/", class: "", id: "ai_012"},
            {name: "ChatExcel", url: "https://chatexcel.com/", class: "", id: "ai_013"},
            {name: "SkillHub", url: "https://skillhub.cloud.tencent.com/", class: "", id: "ai_014"},
            {name: "ChatGPT", url: "https://chat.openai.com/", class: "", id: "ai_015"},
            {name: "文心一言", url: "https://yiyan.baidu.com/", class: "", id: "ai_016"},
            {name: "通义千问", url: "https://tongyi.aliyun.com/", class: "", id: "ai_017"},
            {name: "AI导航", url: "https://ai.seitei.cn/", class: "", id: "ai_018"},
            {name: "开源AI数字人", url: "https://aigcpanel.com/", class: "", id: "ai_019"},
            {name: "讯飞星火", url: "https://xinghuo.xfyun.cn/", class: "", id: "ai_020"},
            {name: "Hermes Agent", url: "https://hermes-agent.nousresearch.com/docs/user-guide/features/tools", class: "", id: "ai_021"},
            {name: "Hermes Agent文挡", url: "https://hermes-doc.aigc.green/", class: "", id: "ai_022"},
            {name: "360智脑", url: "https://ai.360.cn/", class: "", id: "ai_023"},
            {name: "HERMESAGENT中文社区", url: "https://hermesagent.org.cn/", class: "", id: "ai_024"},
            {name: "轩辕镜像", url: "https://xuanyuan.cloud/", class: "", id: "ai_025"},
            {name: "OpenClaw", url: "https://docs.openclaw.ai/zh-CN", class: "", id: "ai_026"},
            {name: "Hermes Agent", url: "https://hermes-agent.org/zh", class: "", id: "ai_027"},
            {name: "OpenClaw教程", url: "https://openclaw-docs.dx3n.cn/tutorials/channels/feishu", class: "", id: "ai_028"},
            {name: "豆包", url: "https://www.doubao.com/chat/", class: "", id: "ai_029"},
            {name: "siliconflow", url: "https://account.siliconflow.cn/zh/login?redirect=https%3A%2F%2Fcloud.siliconflow.cn%2F%3F", class: "", id: "ai_030"},
            {name: "xiaomimimo", url: "https://platform.xiaomimimo.com/docs/zh-CN/welcome", class: "", id: "ai_031"},
            {name: "openai", url: "https://openai.com/zh-Hans-CN/", class: "", id: "ai_032"},
            {name: "Hermes", url: "https://hermesagentai.cn/", class: "", id: "ai_033"},
            {name: "bigmodel", url: "https://bigmodel.cn/", class: "", id: "ai_034"},
            {name: "Openclaw", url: "https://docs.openclaw.ai/zh-CN", class: "", id: "ai_035"}
        ]
    };
}

// 将函数暴露给全局作用域，以便其他脚本使用
window.getDefaultLinkData = getDefaultLinkData;
